// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-KUaHiowGxVfifR-Rq-xp_B5JDRaH4xg',
    appId: '1:508114529190:web:0c8914a196b1abd5a3fd67',
    messagingSenderId: '508114529190',
    projectId: 'servlink-46217',
    authDomain: 'servlink-46217.firebaseapp.com',
    storageBucket: 'servlink-46217.firebasestorage.app',
    measurementId: 'G-VPTSB8MTVQ',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3i1LaxKOLA1xsIqKzEo0MQZpjuHrU32o',
    appId: '1:508114529190:ios:6a94f9fa3c72f2e8a3fd67',
    messagingSenderId: '508114529190',
    projectId: 'servlink-46217',
    storageBucket: 'servlink-46217.firebasestorage.app',
    iosBundleId: 'com.example.servlinkApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3i1LaxKOLA1xsIqKzEo0MQZpjuHrU32o',
    appId: '1:508114529190:ios:6a94f9fa3c72f2e8a3fd67',
    messagingSenderId: '508114529190',
    projectId: 'servlink-46217',
    storageBucket: 'servlink-46217.firebasestorage.app',
    iosBundleId: 'com.example.servlinkApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-KUaHiowGxVfifR-Rq-xp_B5JDRaH4xg',
    appId: '1:508114529190:web:4a2f68f5c9a6146da3fd67',
    messagingSenderId: '508114529190',
    projectId: 'servlink-46217',
    authDomain: 'servlink-46217.firebaseapp.com',
    storageBucket: 'servlink-46217.firebasestorage.app',
    measurementId: 'G-HDMPCR1B15',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPUhda67wMZ9fbF2xffaMKx4NYbnHw-PU',
    appId: '1:508114529190:android:52b6de4e4e56826da3fd67',
    messagingSenderId: '508114529190',
    projectId: 'servlink-46217',
    storageBucket: 'servlink-46217.firebasestorage.app',
  );

}